In [3]:
import pandas as pd

# Load the student performance dataset
pd.read_csv(r"C:\Users\HP\Documents\GitHub\Beta-Anvil\student-performance-analysis\data\StudentsPerformance.csv")
# Preview the first 5 rows

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

from the responsibility given to me the first thing is to load the data set

In [4]:
import pandas as pd

data = pd.read_csv(r"C:\Users\HP\Documents\GitHub\Beta-Anvil\student-performance-analysis\data\StudentsPerformance.csv")

data.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [5]:
math_scores = data["math score"].tolist()

In [6]:
def separate_scores(scores):

    above_70 = []
    below_or_equal_70 = []

    for score in scores:

        if score > 70:
            above_70.append(score)
        else:
            below_or_equal_70.append(score)

    return above_70, below_or_equal_70

In [7]:
high_scores, low_scores = separate_scores(math_scores)

print("Scores above 70:", high_scores[:10])
print("Scores 70 and below:", low_scores[:10])

Scores above 70: [72, 90, 76, 71, 88, 78, 88, 74, 73, 97]
Scores 70 and below: [69, 47, 40, 64, 38, 58, 40, 65, 50, 69]

In [8]:
high_scores, low_scores = separate_scores(math_scores)

print("Scores above 70:", high_scores[:10])
print("Scores 70 and below:", low_scores[:10])

Scores above 70: [72, 90, 76, 71, 88, 78, 88, 74, 73, 97]
Scores 70 and below: [69, 47, 40, 64, 38, 58, 40, 65, 50, 69]

In [3]:
for score in scores:
    # Add your code here
    print(score)  # This is just an example action

NameError: name 'scores' is not defined

In [ ]:
if score > 70:

In [ ]:
else:
    below_or_equal_70.append(score)

In [2]:
return above_70, below_or_equal_70

SyntaxError: 'return' outside function (1830920272.py, line 1)